### ISSUE TITLE
Adding sites crashed app

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/whattemplatemaker#14]
The following workflow leads to a crash in the app:

Press 'Next section' 
On "(2) Site details" unselect `draw spatial boundaries for sites?`
Click `insert row` fast (>3 clicks per second) crashes the app

**Comment by jeffreyhanson** [comment]
Thanks for catching this - I'll look into it.

**Comment by jeffreyhanson** [comment]
This has been fixed by 120818573d7174bc6c1835205065b94091eea790.
