### ISSUE TITLE
Row delete stuck

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/whattemplatemaker#16]
When entering feature information, I stopped at 3 features and then pressed 'Remove row' twice quickly.
Now the app is keeps deleting two rows and adding two rows at least once a second (I can see this like a little animation or rows being added and removed).

Screenshot of setup:
![image](https://user-images.githubusercontent.com/3445092/154071618-9ecdc43e-a2df-4a22-91e7-97d5953253a7.png)

**Comment by ricschuster** [comment]
Quick update: Clicking 'Remove row' just once leads to the same issue.

**Comment by jeffreyhanson** [comment]
Thanks for catching this - I'll look into it.
