### ISSUE TITLE
Action IDs must be unique - should we provide guidance?  

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattemplatemaker#22]
e.g., if they have two separate types of invasive species management? I think people can get around this by manually entering invasive spp management for second instance. Should we make that clearer or is that something for the manual?

**Comment by jeffreyhanson** [comment]
Yeah, good point! I just realized that I never updated the help text (in the left sidebar) after updating the app to allow users to input ids and descriptions -- so I'll update that text now and provide guidance on suitable action ids.
