### ISSUE TITLE
general edits to templatemaker text

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattemplatemaker#27]
I think the template maker is awesome in general. I wonder if we can do a few general edits, consolidating in places and perhaps better linking consequences with goals (because different units may confuse). I'm happy to help and take direction re how to go about editing.

**Comment by jeffreyhanson** [comment]
Thanks! Yeah, if you have any suggestions for improving the text in the template maker app that would be awesome! In terms of editing the text, here's the R file with all the text instructions. You could either submit a PR, or email me an edited version of the file and I can merge that into the application? Would that that work?

**Comment by josephrbennett** [comment]
Did you mean to link to R file in comment above? Sorry if there's something obvious that I missed!

**Comment by jeffreyhanson** [comment]
Ah - yes sorry, here's the file: https://github.com/NCC-CNC/whattemplatemaker/blob/master/R/app_ui.R. All the help text is inside `shiny::helpText()` functions.

**Comment by josephrbennett** [comment]
Suggested changes to text, starting line 101:

 shiny::helpText("Please enter details for each site. Sites include places (or areas) that you are already managing for conservation, or places that you might be considering to acquire for future conservation. For each site, please input a unique identifier (\"id\" column) and a description ( \"description\" column)."),
              shiny::helpText("The identifiers should provide a short name for each site that allows you to easily distinguish among sites. For example, they could be specified using short names (e.g., \"Vulture Valley\"), database codes (e.g., \"12345A\"), or a combination of short names and database codes (e.g., \"Vulture Valley (#12345A)\")."),
              shiny::helpText("The descriptions are used to record additional information on each site, to help understand how each site could be important for conservation management. For instance, the description could discuss presence of a rare species or ecosystem."),
              shiny::helpText("To add a new site, click on the draw button (with the", htmltools::tags$img(src = "www/polygon.svg", style = "display:inline;height:0.8em"), "icon), sketch out the spatial boundary for the site, and then fill in the table with an identifier and description for the site. If you do not wish to draw the site boundaries, you can click the checkbox above the map and enter identifiers and descriptions for the sites directly."),
              shiny::helpText("After you have finished entering in these details, please click the blue arrow in the top right corner of the screen.")

**Comment by josephrbennett** [comment]
shiny::helpText("Please enter details of each feature. These correspond to different biodiversity elements (e.g., populations, species, habitat types, forest cover) for which you wish to improve through effective management (e.g., increase population size, increase amount of available habitat). They can also include ecosystem services (e.g., carbon sequestration) that you wish to promote. For each feature, please input a unique identifier (\"id\" column) and a description ( \"description\" column)."),
              shiny::helpText("The identifiers should provide a short name for each feature that allows you to easily distinguish among the different features. For example, they could be specified using common names (e.g., \"Caribou\", \"Intact alvar\"), scientific names (e.g., \"Rangifer tarandus\"), database codes (e.g., \"12345A\"), or a combination."),
              shiny::helpText("The descriptions are used to record additional information about each feature, to help understand why the feature is important for conservation. For instance, the description could describe threat status (e.g., recorded as Critically Endangered on the IUCN Red List), protection by legislation (e.g., protected by federal-level environmental legislation), or the benefits it provides to humans (e.g., provides carbon sequestration)."),
              shiny::helpText("If you need to add or remove rows, you can click on the buttons above the table. You can also right click on a row and select the relevant option (e.g., \"Insert row above\" or \"Remove row\")."),
              shiny::helpText("After you have finished entering in these details, please click the blue arrow in the top right corner of the screen.")

**Comment by jeffreyhanson** [comment]
This is brilliant - thank you very much @josephrbennett!
