### ISSUE TITLE
What Template Maker failing to load

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattemplatemaker#28]
Could be a more general server issue, though Where to Work appears to load.

Status code: 500

Message: Container did not respond in time

**Comment by jeffreyhanson** [comment]
Just wanted to confirm that I can reproduce this issue, I'll a look and see what I can do.

**Comment by jeffreyhanson** [comment]
N.B. I've pushed a bug fix which fixes the issue in the code, but it might take a short while before these changes appear on the production server.
