### ISSUE TITLE
Example action data

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/whattemplatemaker#3]
As noted in #1, it would be good to include some example actions to help practitioners think of potential actions. @ricschuster and @josephrbennett, when it's ready, could you please post the list of actions we should include in the app here? At the moment, I'm just including some made up example actions in the app to get the functiolity working.

**Comment by ricschuster** [comment]
Here the actions we are using in the survey. More might come in as we get responses, but I think this is a good list to start with:

Land protection (e.g., preventing development)
Restoration (e.g., encouraging native species recovery)
Invasive species management (e.g., identifying new species, controlling populations)
Monitoring (e.g., baseline monitoring, assessing management efficacy)
Fire management
Grazing and/or haying management
Fencing
Forest lot management
Managing visitors and/or access

**Comment by josephrbennett** [comment]
will know more one NCC gets survey back but that seems like a great start to me

**Comment by jeffreyhanson** [comment]
Ok - that's excellent - thanks!

**Comment by jeffreyhanson** [comment]
Per email discssion, here's the default actions:

Wetland and riparian ecosystems:
- Land protection
- Restoration
- Invasive species management
- Managing visitor access

Terrestrial ecosystems:
- Land protection
- Restoration
- Invasive species management
- Grazing and/or haying management
- Fencing
- Forest lot management 
- Managing visitor access

Aquatic ecosystems:
- Restoration
- Grazing and/or haying management
- Managing visitor access
