### ISSUE TITLE
hard to ID which cell has too many characters

### ISSUE THREAD

**Issue by jgvincent** [NCC-CNC/whattemplatemaker#30]
If I input multiple lines over 17 characters, it's difficult to pinpoint which one is too long (the user would need to always pay attention to the alert message in blue at the bottom, which I don't). Can it highlight which boxes are too long? Or stop the user from writing more than 17? Or show how many characters are used (like when writing a tweet, for e.g., 10/17 characters left)?

**Comment by jeffreyhanson** [comment]
Thanks for suggesting this! Yeah, I can definitely look into highlighting cells that contain invalid values. I'll also see if I can update the tables to enforce characters limits on input.
